### PR TITLE
Lr3 viewall posts

### PR DESCRIPTION
**Pull request by lukelr50**

### CODE REVIEW

**Comment by lukelr50** [comment]
Testing


git add / commit what you are working on
git fetch all
git checkout LR3ViewallPosts
data to create Database - https://github.com/NewForce-Cohort-6/tabloidfullstack-cranberry-sauce/blob/main/SQL/01_Tabloid_Create_DB.sql
seed data -  [](https://github.com/NewForce-Cohort-6/tabloidfullstack-cranberry-sauce/blob/main/SQL/02_Tabloid_Seed_Data.sql)

start database from Visual Studio
npm start from client level inside of Tabloid full stack folder

Login using foo@bar.com

navigate to PostManagement using NavBar

Confirm  the posts list a title , author and category.
View table data in database from Posts to confirm that ONLY approved posts are displayed.
Confirm that the only posts that are displayed are ones with a publication date in the past.
Confirm that the posts are ordered by publication date, with the most recent date being at the top.

**Review by jeannettegeib — CHANGES_REQUESTED** [review]
The posts that are in the table as isApproved = false are still showing in this post list. Also all the publication dates in the database are in the past, so I cannot test whether or not publication dates in the future are excluded. Please include an sql query with your instructions to create a post entry with a future publication date so that we can test this aspect of your feature. 
Thank you!
Jeannette

**Review by AllisonCarte — CHANGES_REQUESTED** [review]
Pulled down and tested locally. I'm having the same issues that Jeannette mentioned in her comment. Please fix and then we'll have another look!

Thanks in advance and apologies for the trouble.

**Review by jeannettegeib — APPROVED** [review]

**Review by AllisonCarte — APPROVED** [review]

**Comment by AllisonCarte** [comment]
Required changes were made and things appear to be in order. The post list seems to be filtering for approved posts as well as past publication dates. Everything looks good. Great job, Luke!

**Pull request merged**
